site_name: The Kick Vault
site_url: https://thekickvault.github.io/
repo_url: https://github.com/thekickvault/thekickvault
theme:
  name: material
  language: en
  custom_dir: mkdocs/overrides
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thekickvault
nav:
  - Home: gallery.md
  - About: about.md
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - toc:
      permalink: true
docs_dir: mkdocs
site_dir: docs
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js

