site_name: The Cosmic Vault
site_url: https://thekickvault.github.io/
theme:
  name: material
  language: en
  custom_dir: mkdocs/overrides
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - search.suggest
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thekickvault
nav:
  - Home: index.md
  - R&D: rnd.md
  - Blog: blog.md
  - Soccer Tutorials: tutorials.md
  - Fun: fun.md
  - Contact: contact.md
  - Donate: donate.md
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - toc:
      permalink: true
docs_dir: mkdocs
site_dir: docs
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js

